
export const SEARCH_EMPLOYEE = "SEARCH_EMPLOYEE"
export const SEARCH_EMPLOYEE_SUCCESS = "SEARCH_EMPLOYEE_SUCCESS"
export const SEARCH_EMPLOYEE_FAIL = "SEARCH_EMPLOYEE_FAIL"

export const SAVE_EMPLOYEE = "SAVE_EMPLOYEE"
export const SAVE_EMPLOYEE_SUCCESS = "SAVE_EMPLOYEE_SUCCESS"
export const SAVE_EMPLOYEE_FAIL = "SAVE_EMPLOYEE_FAIL"

export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE"
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS"
export const UPDATE_EMPLOYEE_FAIL = "UPDATE_EMPLOYEE_FAIL"

export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS"
export const DELETE_EMPLOYEE_FAIL = "DELETE_EMPLOYEE_FAIL"

export const EMPLOYEE_FAIL = "EMPLOYEE_FAIL"
